"""Parse a Cursor Agent CLI transcript `.jsonl` into a `session_model.Session`.

Verified against every `~/.cursor/projects/*/agent-transcripts/*/*.jsonl` on
this machine (627 files, 15,845 lines — read only, never copied into the
repo), with `7d8cbab1-0d90-4155-962b-7654f6f5bfcd` (Cursor 2026.08.31, the
first fully sctx-compliant Cursor session) as the S4 validation fixture.

## Transcript location and identity

`~/.cursor/projects/<cwd-slug>/agent-transcripts/<conversation_id>/<conversation_id>.jsonl`,
where `<cwd-slug>` is the session's startup directory with every run of
non-alphanumeric characters collapsed to `-` (so `_` and `/` both become
`-` and the slug is NOT reversible into a path — see `resolve_cwd`).

`<conversation_id>` is simultaneously the hook payload's `conversation_id`
/ `session_id`, the `external_session_id` the model passes to every sctx MCP
tool, and `external_session.external_session_key` with `agent_kind='cursor'`.
One id, no mapping table.

## Line shapes (exhaustive over all 627 files)

Exactly three top-level shapes exist:

  {"role": "user"|"assistant", "message": {"content": [block, ...]}}
  {"type": "turn_ended", "status": "success"}
  {"type": "turn_ended", "status": "error"|"aborted", "error": "<text>"}

and exactly three block shapes:

  {"type": "text", "text": ...}                      (user and assistant)
  {"type": "tool_use", "name": ..., "input": {...}}   (assistant only)

Note what is NOT there, because these absences drive everything below:

  - **No timestamps on any line.** The only clock in the file is the
    `<timestamp>` tag Cursor prepends inside the *user* message text.
  - **No tool_result blocks at all.** Every tool call's output — shell
    output, file contents, and every sctx MCP response — is absent from the
    transcript. (Large outputs are spilled to sibling
    `projects/<slug>/agent-tools/<uuid>.txt` files, but `tool_use` blocks
    carry no id, those files are shared across every conversation in the
    project, and only outputs above some size threshold land there, so they
    cannot be attributed back to a call. They are deliberately not read.)
  - **No hook injections.** Cursor never writes the `additionalContext` a
    hook returns into the transcript, so nothing sctx pushed is visible here.
  - **No tool_use ids, no usage/token records, no git metadata, no cwd, no
    model, no compaction markers.**

## Human prompts vs. the host talking

Every user message wraps the real prompt in `<user_query>...</user_query>`,
usually preceded by `<timestamp>...</timestamp>` and occasionally by a
`<manually_attached_skills>` or `<cursor_commands>` preamble that inlines
skill/command text ahead of the query (1002 timestamped + 70 untimestamped +
45 skill-preamble messages carry a `<user_query>`; 7 do not).

A user message is the HOST talking, not a human, when either:
  - it carries no `<user_query>` at all (observed: "Your previous response
    was interrupted. Continue from where you left off."), or
  - its query text opens with one of `HOST_QUERY_PREFIXES` — Cursor's own
    post-tool / post-subagent continuation prompts ("Briefly inform the user
    about the task result…", "The beginning of the above subagent result is
    already visible…"), which are generated by the client, not typed.

Host-talking user messages do NOT open a new `Turn` (their work folds into
the preceding human turn, exactly as `hosts/codex.py` folds the AGENTS.md
preamble); they are recorded in `Session.other_injections` so the digest
still shows they happened. This keeps `len(session.turns) == human prompts`,
the invariant `bundle.compute_facts` relies on.

## sctx MCP calls

Cursor exposes sctx through a dynamic-tool indirection rather than as native
tools: `tool_use name="GetDynamicTools" input={namespace, toolName|pattern}`
discovers a tool, then `tool_use name="CallDynamicTool"` invokes it with
`input = {namespace, toolName, arguments, mcpDetails?}`. An sctx call is one
whose `namespace` names the `shared-context` MCP server, with or without the
scope prefix Cursor adds -- both `user-shared-context` (110 calls in the real
transcripts here) and bare `shared-context` (47) occur, and which one you get
depends on how the server was registered, not on anything about the call. See
`is_sctx_namespace`. `arguments` is normally an object
but is sometimes a JSON *string* (observed once in the fixture) — both are
accepted and the string is parsed, since `SctxCall.arguments` must be the
full structured arguments for `facts.json`'s claim counting.

Because the transcript holds no results, every `SctxCall` from this host has
`status="unknown"` and `result_text=None`. `error_code` is always None: a
failed sctx call is indistinguishable from a successful one here.

## Injections: reconstructed from sctx, never from the transcript

`reconstruct_from_sctx()` rebuilds the injection timeline out of sctx's own
state, and flags every `Injection` it produces with
`reconstructed_from="sctx:task_injection"`:

  - `runtime.sqlite` `task_injection` rows for this session's task ids, each
    carrying `context_id`, `source` and `injected_at_unix_seconds`. Rows
    sharing a `(source, injected_at_unix_seconds)` pair are one injection
    event, so they are grouped into a single `Injection` whose `ctx_ids` is
    the group. `text` is a synthetic one-line summary and `wire_bytes` /
    `est_tokens` stay 0 — the injected TEXT is nowhere on disk, only the
    identity of what was injected.
  - `~/.shared-context-logs/state/hook-diagnostics.json` `recent_events`
    filtered by `sctx_logs.telemetry_session_digest("cursor", <id>)`. The
    digest formula is host-agnostic and gated on `{"cursor","codex"}` in the
    Rust source, and it matches for real Cursor sessions (verified: 328
    events for the fixture, `hook.cursor.session_start` through
    `hook.cursor.turn_stop`). These become per-turn `HookEvent` aggregates,
    not `Injection`s — they say a hook ran, not that context arrived.

Both are bucketed into turns by the `<timestamp>` clock: turn *n* owns
`[start_n, start_{n+1})`, with turn 1's lower bound open (so the
session_start hook, which fires seconds before the first prompt is stamped,
lands in turn 1) and the last turn's upper bound open. Cursor stamps
timestamps only to the minute, so a row within ~60s of a turn boundary can
land on either side; anything that cannot be bucketed at all (no timestamps
in the transcript, or the session has no turns) is reported under
`Session.reconstruction["unwindowed"]` instead of being guessed into a turn.
"""
from __future__ import annotations

import contextlib
import datetime as dt
import json
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import sctx_logs  # noqa: E402
from session_model import (  # noqa: E402
    HookEvent,
    Injection,
    OtherInjection,
    SctxCall,
    Session,
    SessionMeta,
    ToolCall,
    Turn,
)

# The `namespace` on a dynamic-tool call is the MCP SERVER name as Cursor
# resolved it, and Cursor prefixes it with the scope the server was registered
# in. Both spellings occur in real transcripts on this machine
# (`user-shared-context` 110×, `shared-context` 47×), and the S4 replay
# produced the unprefixed one from an isolated CURSOR_CONFIG_DIR while the
# original produced the prefixed one -- so matching the literal string would
# have found zero sctx calls in the replay of a session full of them. Match the
# server name with any scope prefix instead.
SCTX_SERVER_NAME = "shared-context"
DYNAMIC_CALL_TOOL = "CallDynamicTool"
DYNAMIC_DISCOVER_TOOL = "GetDynamicTools"


def is_sctx_namespace(namespace) -> bool:
    if not isinstance(namespace, str):
        return False
    return namespace == SCTX_SERVER_NAME or namespace.endswith(f"-{SCTX_SERVER_NAME}")

USER_QUERY_RE = re.compile(r"<user_query>(.*?)</user_query>", re.DOTALL)
TIMESTAMP_RE = re.compile(r"<timestamp>(.*?)</timestamp>", re.DOTALL)

# Cursor's own continuation prompts. They arrive as `role: "user"` messages
# with a normal `<user_query>` wrapper, but no human typed them: the client
# emits them after a queued tool run or a finished subagent. Replaying one
# would fabricate a prompt the original human never sent.
HOST_QUERY_PREFIXES = (
    "Briefly inform the user about the task result",
    "The beginning of the above subagent result is already visible",
    "Your previous response was interrupted",
)

FIDELITY_NOTES = (
    "tool outputs are NOT recorded by Cursor: every tool_use block in the "
    "transcript has no paired result, so sctx MCP responses (accept/reject, "
    "returned candidates, returned context packs) are unavailable — "
    "sctx_calls carry status=unknown and no result text",
    "hook injections are NOT recorded by Cursor: the transcript never shows "
    "what sctx pushed, so every injection below is RECONSTRUCTED from sctx's "
    "own runtime.sqlite/task_injection rows — the context ids and the time "
    "are real, the injected text is unrecoverable and wire_bytes/est_tokens "
    "are therefore 0, not measured",
    "no token usage, git commit, model or compaction markers are recorded by "
    "Cursor; those fields are empty rather than zero-valued findings",
)

# task_injection.source -> Injection.kind. Observed values across the real
# database: intent_update (170), task_context (7), artifact_focus (2). The
# host-agnostic kinds in session_model are Codex-hook-shaped, and none of
# these map onto them cleanly, so the sctx source name is kept verbatim and
# prefixed to stay obviously distinct from a transcript-read Codex kind.
def _injection_kind(source: Optional[str]) -> str:
    return f"sctx:{source}" if source else "sctx:unknown"


def slugify_cwd(path: str) -> str:
    """Reproduces Cursor's project-directory slug for a startup directory.

    Verified against the real project directories on this machine:
    `/Users/<user>/work/cross/fe/search_web_monorepo` ->
    `Users-<user>-work-cross-fe-search-web-monorepo`. The mapping is
    lossy (both `/` and `_` become `-`), which is why `resolve_cwd` searches
    candidate paths forward through this function instead of inverting it.
    """
    return re.sub(r"[^A-Za-z0-9]+", "-", path).strip("-")


def resolve_transcript(
    conversation_id: str, cursor_home: Optional[Path] = None
) -> Optional[Path]:
    """Resolve a Cursor conversation id to its transcript `.jsonl`.

    `cursor_home` defaults to `~/.cursor` (Cursor's own state; independent of
    the sctx `--home` flag). The conversation id is globally unique across
    projects, so the project slug does not need to be known in advance.
    """
    home = cursor_home or (Path.home() / ".cursor")
    projects = home / "projects"
    if not projects.is_dir():
        return None
    direct = sorted(
        projects.glob(f"*/agent-transcripts/{conversation_id}/{conversation_id}.jsonl")
    )
    if direct:
        return direct[0]
    loose = sorted(projects.glob(f"*/agent-transcripts/{conversation_id}/*.jsonl"))
    return loose[0] if loose else None


def resolve_cwd(
    transcript: Path,
    home: Optional[Path] = None,
    external_session_id: Optional[str] = None,
) -> tuple[Optional[str], str]:
    """Recover the session's startup directory. Returns `(cwd, how)`.

    Cursor records the cwd nowhere in the transcript, and its project slug is
    lossy. Two sources, best first:

    1. **The sctx activation lease.** `sctx_facts.get_lease_facts` reads
       `<home>/.shared-context/state/authorized-session-scopes/scope-<digest>.json`,
       which stores `startup_cwd` verbatim. Exact, but only present until
       SessionEnd (or the 30-day reclaim) removes the lease.
    2. **Slug match against the registered Shared Context checkouts.** Every
       registered checkout path is slugified and compared to the transcript's
       project directory name; a unique hit is the cwd. Ambiguity or no hit
       returns None and the caller must be told the cwd.
    """
    import sctx_facts  # local import: avoids a cycle at module import time

    home = home or Path.home()
    if external_session_id:
        lease = sctx_facts.get_lease_facts(home, "cursor", external_session_id)
        cwd = lease.get("lease_startup_cwd")
        if cwd:
            return str(cwd), "sctx activation lease (startup_cwd)"

    slug = transcript.parent.parent.parent.name
    config = home / ".shared-context" / "config.toml"
    if config.is_file():
        try:
            body = config.read_text(encoding="utf-8")
        except OSError:
            body = ""
        candidates = sorted(
            {path for path in re.findall(r'"(/[^"]+)"', body) if slugify_cwd(path) == slug}
        )
        if len(candidates) == 1:
            return candidates[0], "slug match against a registered Shared Context checkout"
        if len(candidates) > 1:
            return None, f"slug {slug!r} matches {len(candidates)} registered checkouts"
    return None, f"slug {slug!r} matches no registered checkout and no lease survives"


def parse_cursor_timestamp(text: str) -> Optional[dt.datetime]:
    """Parse a `<timestamp>` tag body into an aware datetime.

    Real shape: `Tuesday, Sep 8, 2026, 10:27 PM (UTC+8)`. Minute granularity
    (verified against the fixture's own session-start lease at 22:27:34, i.e.
    the tag rounds down), so callers must treat bucket boundaries as fuzzy to
    within a minute.
    """
    match = re.search(
        r"([A-Z][a-z]{2})\s+(\d{1,2}),\s*(\d{4}),\s*(\d{1,2}):(\d{2})\s*([AP]M)"
        r"(?:\s*\(UTC([+-]\d{1,2})(?::(\d{2}))?\))?",
        text,
    )
    if not match:
        return None
    month, day, year, hour, minute, meridiem, tz_hours, tz_minutes = match.groups()
    try:
        stamp = dt.datetime.strptime(
            f"{month} {day} {year} {hour}:{minute} {meridiem}", "%b %d %Y %I:%M %p"
        )
    except ValueError:
        return None
    if tz_hours is None:
        return stamp.replace(tzinfo=dt.timezone.utc)
    offset = dt.timedelta(hours=int(tz_hours), minutes=int(tz_minutes or 0))
    if tz_hours.startswith("-"):
        offset = dt.timedelta(hours=int(tz_hours), minutes=-int(tz_minutes or 0))
    return stamp.replace(tzinfo=dt.timezone(offset))


def split_user_message(text: str) -> tuple[Optional[str], Optional[dt.datetime], str]:
    """Split a Cursor user message into `(query, timestamp, preamble)`.

    `query` is the verbatim `<user_query>` body — what a human actually typed
    and what a replay must resubmit — or None when the message carries no
    query tag at all. `preamble` is everything outside the query tag (the
    timestamp tag, an inlined skill bundle, a `<cursor_commands>` block),
    kept only so the digest can show that it was there.
    """
    stamp = None
    stamp_match = TIMESTAMP_RE.search(text)
    if stamp_match:
        stamp = parse_cursor_timestamp(stamp_match.group(1))
    query_match = USER_QUERY_RE.search(text)
    if not query_match:
        return None, stamp, text
    query = query_match.group(1).strip()
    preamble = (text[: query_match.start()] + text[query_match.end():]).strip()
    return query, stamp, preamble


def is_human_prompt(query: Optional[str]) -> bool:
    if not query:
        return False
    return not query.lstrip().startswith(HOST_QUERY_PREFIXES)


def _blocks(record: dict) -> list:
    message = record.get("message")
    if not isinstance(message, dict):
        return []
    content = message.get("content")
    return content if isinstance(content, list) else []


def _joined_text(blocks: list) -> str:
    return "".join(
        block.get("text", "")
        for block in blocks
        if isinstance(block, dict) and block.get("type") == "text"
    )


ARGUMENTS_UNPARSED_KEY = "__arguments_unparsed__"


def _arguments(raw: Any) -> dict:
    """Normalize `CallDynamicTool.input.arguments` into a dict.

    Usually an object. Sometimes a JSON *string* — and in the fixture the one
    string-valued case is TRUNCATED mid-object (2074 chars ending
    `..."unknowns":[]` with no closing brace), i.e. the host recorded a
    partial tool call. That is a real finding, not a parser problem, so the
    failure is preserved verbatim under `__arguments_unparsed__` instead of
    being silently dropped or hand-repaired; `bundle.compute_facts` counts
    these separately and excludes them from the
    `external_session_id_verbatim` check, which they would otherwise fail for
    the wrong reason.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError as error:
            return {
                ARGUMENTS_UNPARSED_KEY: True,
                "__arguments_error__": str(error),
                "__arguments_chars__": len(raw),
                "__arguments_text__": raw,
            }
        return parsed if isinstance(parsed, dict) else {"__arguments__": parsed}
    if raw is None:
        return {}
    return {"__arguments__": raw}


def _read_lines(path: Path):
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def parse_transcript(path: Path, conversation_id: Optional[str] = None) -> Session:
    """Parse a Cursor transcript into a `Session` with no sctx-side data.

    Call `reconstruct_from_sctx()` afterwards to fill in the injections and
    hook events, which this host's transcript cannot supply.
    """
    session = Session(
        meta=SessionMeta(
            host="cursor",
            thread_id=conversation_id or path.stem,
            fidelity_notes=list(FIDELITY_NOTES),
        )
    )
    builder: Optional[Turn] = None

    for record in _read_lines(path):
        if record.get("type") == "turn_ended":
            status = record.get("status")
            if status != "success" and builder is not None:
                error = record.get("error")
                session.other_injections.append(
                    OtherInjection(text_head=f"turn_ended status={status} error={error}"[:80])
                )
            continue

        role = record.get("role")
        blocks = _blocks(record)

        if role == "user":
            text = _joined_text(blocks)
            query, stamp, preamble = split_user_message(text)
            if not is_human_prompt(query):
                head = (query or text).strip().replace("\n", " ")
                session.other_injections.append(
                    OtherInjection(text_head=f"cursor host prompt: {head}"[:80])
                )
                continue
            builder = Turn(
                index=len(session.turns) + 1,
                user_text=query or "",
                started_at=stamp.isoformat() if stamp else None,
            )
            session.turns.append(builder)
            if preamble and "<manually_attached_skills>" in preamble:
                session.other_injections.append(
                    OtherInjection(
                        text_head=f"turn {builder.index} preamble: "
                        f"<manually_attached_skills> ({len(preamble)} chars)"[:80]
                    )
                )
            elif preamble and "<cursor_commands>" in preamble:
                session.other_injections.append(
                    OtherInjection(
                        text_head=f"turn {builder.index} preamble: "
                        f"<cursor_commands> ({len(preamble)} chars)"[:80]
                    )
                )
            continue

        if role != "assistant":
            continue

        for block in blocks:
            if not isinstance(block, dict):
                continue
            kind = block.get("type")
            if kind == "text":
                if builder is not None and block.get("text"):
                    builder.assistant_texts.append(block["text"])
                continue
            if kind != "tool_use":
                continue
            name = block.get("name", "")
            payload = block.get("input")
            payload = payload if isinstance(payload, dict) else {}
            args_text = json.dumps(payload, ensure_ascii=False)
            if builder is None:
                continue
            builder.tool_calls.append(ToolCall(name=name, args_head=args_text[:160]))
            if name == DYNAMIC_CALL_TOOL and is_sctx_namespace(payload.get("namespace")):
                builder.sctx_calls.append(
                    SctxCall(
                        tool=payload.get("toolName") or "",
                        arguments=_arguments(payload.get("arguments")),
                        # Cursor records no tool results at all, so neither the
                        # outcome nor an error code of this call is knowable
                        # from the transcript. `sctx/*.json` in the bundle is
                        # the only place an accept/reject can be checked.
                        status="unknown",
                        result_text=None,
                        error_code=None,
                    )
                )

    if session.turns:
        session.meta.started_at = session.turns[0].started_at
        session.meta.ended_at = session.turns[-1].started_at
    session.meta.cli_version = ""
    session.meta.originator = "cursor-agent"
    return session


# --------------------------------------------------------------------------
# Reconstructing what the transcript cannot show
# --------------------------------------------------------------------------


def _turn_windows(session: Session) -> list:
    """`[(turn, lower_epoch_or_None, upper_epoch_or_None)]`, turn 1's lower
    bound and the last turn's upper bound left open. Returns [] when no turn
    carries a timestamp, which is how pre-timestamp transcripts degrade."""
    starts = []
    for turn in session.turns:
        if turn.started_at:
            starts.append(dt.datetime.fromisoformat(turn.started_at).timestamp())
        else:
            starts.append(None)
    if not any(start is not None for start in starts):
        return []
    windows = []
    for position, turn in enumerate(session.turns):
        lower = None if position == 0 else starts[position]
        upper = starts[position + 1] if position + 1 < len(starts) else None
        windows.append((turn, lower, upper))
    return windows


def _bucket(windows: list, when: Optional[float]) -> Optional[Turn]:
    if when is None or not windows:
        return None
    for turn, lower, upper in windows:
        if (lower is None or when >= lower) and (upper is None or when < upper):
            return turn
    return None


def _task_injection_rows(db_path: Path, external_session_id: str) -> tuple[list, Optional[str]]:
    """All `task_injection` rows for one Cursor session, joined the same way
    `sctx_facts.get_session_facts` joins them (external_session ->
    task_session -> task_id), plus the `xss_...` id for the manifest."""
    if not db_path.exists():
        return [], None
    try:
        with contextlib.closing(
            sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        ) as connection:
            connection.row_factory = sqlite3.Row
            external = connection.execute(
                "SELECT external_session_id FROM external_session "
                "WHERE agent_kind = 'cursor' AND external_session_key = ?",
                (external_session_id,),
            ).fetchone()
            if external is None:
                return [], None
            xss_id = external["external_session_id"]
            task_ids = [
                row["task_id"]
                for row in connection.execute(
                    "SELECT task_id FROM task_session WHERE external_session_id = ?",
                    (xss_id,),
                )
            ]
            if not task_ids:
                return [], xss_id
            placeholders = ",".join("?" for _ in task_ids)
            rows = [
                dict(row)
                for row in connection.execute(
                    f"SELECT * FROM task_injection WHERE task_id IN ({placeholders}) "  # noqa: S608
                    "ORDER BY injected_at_unix_seconds",
                    tuple(task_ids),
                )
            ]
            return rows, xss_id
    except sqlite3.DatabaseError:
        return [], None


def _group_injections(rows: list) -> list:
    """Group `task_injection` rows into injection EVENTS.

    One `sctx` push writes one row per injected context id, all sharing a
    `(source, injected_at_unix_seconds)` pair — the fixture's 20 rows are 3
    events (3 + 4 + 13). Reporting 20 injections would triple-count the pushes
    and make `injections.count` incomparable with the Codex side.
    """
    grouped: dict = {}
    for row in rows:
        key = (row.get("source"), int(row.get("injected_at_unix_seconds") or 0))
        grouped.setdefault(key, []).append(row)
    events = []
    for (source, when), members in sorted(grouped.items(), key=lambda item: item[0][1]):
        ctx_ids = sorted({row.get("context_id") for row in members if row.get("context_id")})
        revisions = sorted({row.get("intent_revision_id") for row in members if row.get("intent_revision_id")})
        events.append(
            {
                "source": source,
                "injected_at_unix_seconds": when,
                "ctx_ids": ctx_ids,
                "intent_revision_ids": revisions,
                "row_count": len(members),
            }
        )
    return events


def _event_to_injection(event: dict) -> Injection:
    when = dt.datetime.fromtimestamp(
        event["injected_at_unix_seconds"], dt.timezone.utc
    ).isoformat()
    summary = (
        f"[reconstructed from sctx runtime.sqlite/task_injection] "
        f"source={event['source']} injected_at={when} "
        f"context_ids={len(event['ctx_ids'])} "
        f"intent_revision_ids={','.join(event['intent_revision_ids']) or '-'}\n"
        f"{chr(10).join(event['ctx_ids'])}\n"
        "(the injected TEXT is not recorded anywhere on this host: Cursor does "
        "not write hook additionalContext into its transcript, and sctx stores "
        "only the identity of what it injected)"
    )
    return Injection(
        kind=_injection_kind(event["source"]),
        text=summary,
        has_marker=False,
        marker_session_id=None,
        ctx_ids=event["ctx_ids"],
        # Deliberately 0, not a guess: the delivered bytes are unmeasurable
        # here, and a fabricated number would be compared against Codex's real
        # one in facts.json.
        wire_bytes=0,
        est_tokens=0,
        truncated=False,
        reconstructed_from="sctx:task_injection",
    )


def _aggregate_hook_events(events: list) -> list:
    grouped: dict = {}
    for event in events:
        key = (event.get("operation"), event.get("outcome"), event.get("reason"))
        bucket = grouped.setdefault(key, [])
        bucket.append(event.get("occurred_at_unix_ms"))
    aggregated = []
    for (operation, outcome, reason), stamps in grouped.items():
        clean = sorted(stamp for stamp in stamps if stamp is not None)
        aggregated.append(
            HookEvent(
                operation=operation or "",
                outcome=outcome or "",
                reason=reason,
                count=len(stamps),
                first_at_unix_ms=clean[0] if clean else None,
                last_at_unix_ms=clean[-1] if clean else None,
            )
        )
    return sorted(aggregated, key=lambda item: (item.first_at_unix_ms or 0, item.operation))


def reconstruct_from_sctx(
    session: Session,
    home: Path,
    external_session_id: Optional[str] = None,
) -> dict:
    """Fill in `Turn.injections` and `Turn.hook_events` from sctx's own state.

    Mutates `session` and returns (and stores on `session.reconstruction`) the
    provenance record: which files were read, what the per-turn windows were,
    and which rows could not be attributed to a turn.
    """
    session_id = external_session_id or session.meta.thread_id
    db_path = home / ".shared-context" / "state" / "runtime.sqlite"
    logs_root = home / ".shared-context-logs"

    rows, xss_id = _task_injection_rows(db_path, session_id)
    events = _group_injections(rows)

    digest = sctx_logs.telemetry_session_digest("cursor", session_id)
    diagnostics_path = logs_root / "state" / "hook-diagnostics.json"
    hook_events: list = []
    # `hook-diagnostics.json` is written by the sctx LOG COLLECTOR service, not
    # by the hooks themselves. A replay HOME starts with an empty
    # `.shared-context-logs/` and no collector running in it, so the file is
    # simply absent there -- which must not be reported as "no hooks ran". The
    # replay's own hook traffic is captured by `replay_cursor.py` into
    # `host/hook-input.jsonl` / `host/hook-output.jsonl` and summarised in
    # `manifest.isolation.hooks` instead.
    if not diagnostics_path.is_file():
        hook_source = f"unavailable: {diagnostics_path} does not exist"
    elif not digest:
        hook_source = "unavailable: no telemetry digest for this session id"
    else:
        hook_source = str(diagnostics_path)
        try:
            with open(diagnostics_path, "r", encoding="utf-8") as handle:
                diagnostics = json.load(handle)
            hook_events = [
                event
                for event in (diagnostics.get("recent_events") or [])
                if event.get("session_digest") == digest
            ]
        except (OSError, json.JSONDecodeError) as error:
            hook_source = f"unreadable: {diagnostics_path} ({error})"

    windows = _turn_windows(session)
    unwindowed_injections: list = []
    unwindowed_hook_events: list = []

    for event in events:
        turn = _bucket(windows, float(event["injected_at_unix_seconds"]))
        if turn is None:
            unwindowed_injections.append(event)
        else:
            turn.injections.append(_event_to_injection(event))

    per_turn_hooks: dict = {}
    for event in hook_events:
        stamp = event.get("occurred_at_unix_ms")
        turn = _bucket(windows, stamp / 1000.0 if stamp is not None else None)
        if turn is None:
            unwindowed_hook_events.append(event)
        else:
            per_turn_hooks.setdefault(turn.index, []).append(event)
    for turn in session.turns:
        turn.hook_events = _aggregate_hook_events(per_turn_hooks.get(turn.index, []))

    record = {
        "source": "sctx",
        "reason": (
            "Cursor transcripts record neither hook injections nor tool "
            "results; injections and hook events below are rebuilt from "
            "sctx's own state and are flagged reconstructed_from"
        ),
        "runtime_sqlite": str(db_path),
        "external_session_id": xss_id,
        "hook_diagnostics": str(diagnostics_path),
        "hook_diagnostics_available": not hook_source.startswith(("unavailable", "unreadable")),
        "hook_diagnostics_source": hook_source,
        "hook_diagnostics_session_digest": digest,
        "task_injection_rows": len(rows),
        "task_injection_events": len(events),
        "hook_diagnostics_events": len(hook_events),
        "turn_windows": [
            {
                "turn": turn.index,
                "started_at": turn.started_at,
                "lower_unix_seconds": lower,
                "upper_unix_seconds": upper,
            }
            for turn, lower, upper in windows
        ],
        "windowing": (
            "per-turn (<timestamp> tags present; minute granularity, so rows "
            "within ~60s of a boundary may fall on either side)"
            if windows
            else "session-level only (no <timestamp> tag in any user message)"
        ),
        "unwindowed": {
            "injection_events": unwindowed_injections,
            "injection_ctx_ids": sorted(
                {ctx for event in unwindowed_injections for ctx in event["ctx_ids"]}
            ),
            "hook_event_count": len(unwindowed_hook_events),
            "hook_events": _serialize_hook_events(
                _aggregate_hook_events(unwindowed_hook_events)
            ),
        },
    }
    session.reconstruction = record
    return record


def _serialize_hook_events(events: list) -> list:
    return [
        {
            "operation": event.operation,
            "outcome": event.outcome,
            "reason": event.reason,
            "count": event.count,
            "first_at_unix_ms": event.first_at_unix_ms,
            "last_at_unix_ms": event.last_at_unix_ms,
        }
        for event in events
    ]


def load_session(
    conversation_id: str,
    home: Optional[Path] = None,
    cursor_home: Optional[Path] = None,
    transcript: Optional[Path] = None,
    reconstruct: bool = True,
) -> tuple[Session, Optional[Path]]:
    """Resolve, parse and (by default) reconstruct one Cursor session."""
    home = home or Path.home()
    path = transcript or resolve_transcript(conversation_id, cursor_home=cursor_home)
    if path is None:
        return Session(meta=SessionMeta(host="cursor", thread_id=conversation_id)), None
    session = parse_transcript(path, conversation_id=conversation_id)
    cwd, how = resolve_cwd(path, home=home, external_session_id=conversation_id)
    if cwd:
        session.meta.cwd = cwd
        session.meta.fidelity_notes.append(f"cwd recovered via {how}")
    else:
        session.meta.fidelity_notes.append(f"cwd unknown: {how}")
    if reconstruct:
        reconstruct_from_sctx(session, home, external_session_id=conversation_id)
    return session, path
