//! The F2LLM-v2-0.6B encoder contract, checked against a reference implementation's own numbers.
//!
//! Every way this family can be wired up wrongly produces a unit-length 1024-wide vector. A missing
//! query instruction, a `position_ids` input the graph never receives, CLS pooling where the
//! sentence lives in the last position, a truncation that drops the `<|im_end|>` that last-token
//! pooling reads -- none of them errors, none of them changes a shape, and all of them silently move
//! every vector into a space where the corpus and the query no longer mean the same thing. There is
//! no assertion available at the vector, so this suite asserts one layer earlier, on the exact token
//! sequence, and then confirms the vector against numbers produced outside this workspace.
//!
//! `tests/fixtures/f2llm_golden.json` holds those numbers: for four texts, the `input_ids` the
//! Hugging Face tokenizer produces and the first sixteen dimensions of the vector `onnxruntime`
//! returns for them, generated by a Python reference that had already been checked at cosine 0.998
//! against `sentence-transformers`. Two of the four are queries, carrying the instruction prefix,
//! and two are documents, carrying none -- because the asymmetry is the part a codebase built around
//! a symmetric model is most likely to drop.
//!
//! `#[ignore]`d because it needs roughly 2.4 GB of weights this repository deliberately does not
//! ship. Point it at an unmodified Hugging Face snapshot and the ONNX Runtime library:
//!
//! ```text
//! SCTX_PROBE_F2LLM_MODEL=~/.cache/huggingface/hub/models--codefuse-ai--F2LLM-v2-0.6B/snapshots/<sha> \
//! SCTX_PROBE_EMBEDDING_RUNTIME=~/.shared-context/embedding/runtime/libonnxruntime.dylib \
//!   cargo test -p sctx-search --test embedding_f2llm_contract -- --ignored --nocapture
//! ```
//!
//! `f2llm_snapshot` reshapes that snapshot into the flat directory the provider loads from and holds
//! the one session this binary uses.

#![cfg(all(feature = "embedding-onnx", unix))]

mod f2llm_snapshot;

use f2llm_snapshot::provider;
use sctx_search::{
    EmbeddingProvider,
    embedding::{
        SEMANTIC_MAX_TOKENS,
        onnx::{ModelFamily, TextRole},
    },
};
use serde_json::Value;

const GOLDEN: &str = include_str!("fixtures/f2llm_golden.json");

/// How close a vector has to be to the reference's to count as the same vector.
///
/// Not equality: the fixture stores six decimal places and the two runs allocate their own arenas,
/// so the last bits of a float are not a contract. 0.999 over sixteen dimensions is still far
/// tighter than any failure this file guards against -- dropping the query instruction moves a
/// vector by vastly more than a thousandth.
const VECTOR_AGREEMENT: f32 = 0.999;

/// Dimensions of the vector head the fixture stores.
const HEAD: usize = 16;

/// The hidden size an F2LLM-v2-0.6B vector must have.
const HIDDEN_SIZE: usize = 1024;

/// `<|im_end|>`, which last-token pooling reads and truncation must therefore preserve.
const EOS_TOKEN: i64 = 151_645;

fn golden_cases() -> Vec<Value> {
    let golden: Value = serde_json::from_str(GOLDEN).expect("the golden fixture is valid JSON");
    golden["cases"]
        .as_array()
        .expect("the golden fixture holds a case array")
        .clone()
}

fn golden_field<'a>(case: &'a Value, field: &str) -> &'a Value {
    case.get(field)
        .unwrap_or_else(|| panic!("golden case has no {field}"))
}

fn golden_text(case: &Value) -> &str {
    golden_field(case, "text")
        .as_str()
        .expect("golden text is a string")
}

fn golden_role(case: &Value) -> TextRole {
    match golden_field(case, "role").as_str() {
        Some("query") => TextRole::Query,
        Some("document") => TextRole::Document,
        other => panic!("golden case has an unknown role {other:?}"),
    }
}

fn golden_input_ids(case: &Value) -> Vec<i64> {
    golden_field(case, "input_ids")
        .as_array()
        .expect("golden input_ids is an array")
        .iter()
        .map(|id| id.as_i64().expect("golden input_ids holds integers"))
        .collect()
}

fn golden_head(case: &Value) -> Vec<f32> {
    golden_field(case, "vector_head_16")
        .as_array()
        .expect("golden vector head is an array")
        .iter()
        .map(|value| {
            let value = value.as_f64().expect("golden vector head holds floats");
            #[allow(clippy::cast_possible_truncation)]
            {
                value as f32
            }
        })
        .collect()
}

/// Cosine of two vectors of any length, normalising both: the fixture head is a slice of a unit
/// vector and so is not itself unit length.
fn cosine(left: &[f32], right: &[f32]) -> f32 {
    assert_eq!(
        left.len(),
        right.len(),
        "compared vectors of unequal length"
    );
    let dot = left
        .iter()
        .zip(right)
        .map(|(left, right)| left * right)
        .sum::<f32>();
    let norm = |values: &[f32]| values.iter().map(|value| value * value).sum::<f32>().sqrt();
    dot / (norm(left) * norm(right))
}

#[test]
#[ignore = "needs a real F2LLM-v2-0.6B snapshot; see the module docs"]
fn the_f2llm_encoder_reproduces_the_reference_tokens_and_vectors() {
    let provider = provider();

    assert_eq!(
        provider.family(),
        ModelFamily::Qwen3,
        "an F2LLM snapshot carries config.json model_type qwen3; anything else means family \
         detection read the wrong thing"
    );
    for case in golden_cases() {
        let text = golden_text(&case);
        let role = golden_role(&case);

        // Tokens first. The vector comparison below cannot tell "the sequence was right" from "the
        // sequence was wrong the same way on both sides"; this can.
        let ids = provider
            .input_ids(text, role)
            .expect("tokenize the golden case");
        assert_eq!(
            ids,
            golden_input_ids(&case),
            "token sequence diverged from the reference for the {role:?} case {text:?}; a \
             last-token-pooled vector over a different sequence is silently a different vector"
        );

        let vector = match role {
            TextRole::Query => provider.encode(text),
            TextRole::Document => provider.encode_bulk(text),
        }
        .expect("encode the golden case");
        assert_eq!(
            vector.len(),
            HIDDEN_SIZE,
            "a width other than the model's hidden size means a different pooling ran"
        );
        let agreement = cosine(&vector[..HEAD], &golden_head(&case));
        assert!(
            agreement >= VECTOR_AGREEMENT,
            "the {role:?} case {text:?} agrees with the reference vector at only {agreement}, \
             under {VECTOR_AGREEMENT}"
        );
    }
}

#[test]
#[ignore = "needs a real F2LLM-v2-0.6B snapshot; see the module docs"]
fn truncation_keeps_the_token_last_token_pooling_reads() {
    let provider = provider();

    // Comfortably past the cap in any tokenization, so the post-processor's trailing token is
    // certainly cut by the truncation and has to be put back.
    let long = "推送去重窗口与重试间隔的关系需要逐条说明。".repeat(200);
    let ids = provider
        .input_ids(&long, TextRole::Document)
        .expect("tokenize a text past the truncation ceiling");

    assert_eq!(
        ids.len(),
        SEMANTIC_MAX_TOKENS,
        "a text past the cap is truncated to the cap with EOS inside it, not to the cap plus one"
    );
    assert_eq!(
        ids.last().copied(),
        Some(EOS_TOKEN),
        "truncation cuts from the right, which is where <|im_end|> is; without it the vector means \
         the 511th token of the text rather than the text"
    );
    provider
        .encode_bulk(&long)
        .expect("a truncated text still encodes");
}

#[test]
#[ignore = "needs a real F2LLM-v2-0.6B snapshot; see the module docs"]
fn the_query_instruction_stays_inside_the_provider() {
    let provider = provider();
    let cases = golden_cases();
    let query = cases
        .iter()
        .find(|case| golden_role(case) == TextRole::Query)
        .expect("the fixture holds a query case");
    let query_text = golden_text(query);

    // The instruction reaches the tokenizer, and only on the query side.
    let as_query = provider
        .input_ids(query_text, TextRole::Query)
        .expect("query tokens");
    let as_document = provider
        .input_ids(query_text, TextRole::Document)
        .expect("document tokens");
    assert!(
        as_query.len() > as_document.len(),
        "without the instruction every query is embedded as though it were corpus text"
    );
    // And the text survives the prefix intact -- but not token-for-token, because the instruction
    // ends in a space and this tokenizer is byte-level BPE: the boundary space merges into the
    // query's first token, so `as_query` ends with the tokens of " {query}" rather than of
    // "{query}". That is the reference implementation's behaviour too, which is why the golden
    // sequence above matches; asserting the naive suffix here would be asserting a property Python
    // does not have either. What must hold is that the provider prefixes and does nothing else:
    // everything after the instruction is exactly what the tokenizer makes of the query text in the
    // position the instruction leaves it in.
    let after_instruction = provider
        .input_ids(&format!(" {query_text}"), TextRole::Document)
        .expect("tokens for the query text in the position the instruction leaves it in");
    assert!(
        as_query.ends_with(&after_instruction),
        "the instruction is a prefix and nothing more: the query text must reach the model \
         unaltered behind it"
    );

    // And it never escapes the provider: a caller hands `encode` the text a session asked about
    // and gets the prefixed encoding back, without ever seeing the prefix. The check used to run
    // through the channel's query vector cache, which was keyed on the raw text; ADR-0007 retired
    // that cache along with the query path, so it is asked of the provider directly, which is
    // where the asymmetry has always lived.
    let encoded = provider
        .encode(query_text)
        .expect("encode the query text through the interactive path");
    let agreement = cosine(&encoded[..HEAD], &golden_head(query));
    assert!(
        agreement >= VECTOR_AGREEMENT,
        "the vector `encode` returns for the raw text is the prefixed encoding, not an unprefixed \
         one: agreement {agreement}"
    );
}
